[package]
name = "qwen-proxy-rs"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
path = "src/lib.rs"

[dependencies]
anyhow.workspace = true
async-stream.workspace = true
axum.workspace = true
base64.workspace = true
browser-bridge = { path = "../browser-bridge" }
bytes.workspace = true
clap.workspace = true
futures-util.workspace = true
hmac.workspace = true
httpdate.workspace = true
mime_guess.workspace = true
once_cell.workspace = true
proxy-core = { path = "../proxy-core" }
reqwest.workspace = true
rusqlite.workspace = true
serde.workspace = true
serde_json.workspace = true
sha1.workspace = true
sha2.workspace = true
sysinfo.workspace = true
tokio.workspace = true
tokio-util.workspace = true
url.workspace = true
uuid.workspace = true
