[package]
name = "kimi-proxy-rs"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
async-stream.workspace = true
axum.workspace = true
browser-bridge = { path = "../browser-bridge" }
bytes.workspace = true
clap.workspace = true
futures-util.workspace = true
once_cell.workspace = true
proxy-core = { path = "../proxy-core" }
regex.workspace = true
reqwest.workspace = true
serde_json.workspace = true
tokio.workspace = true
tower-http.workspace = true
uuid.workspace = true
